// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Heartbeat          string
	Mempool            string
	MempoolBin         string
	NetworkSnapshot    string
	NetworkSnapshotBin string
	Node               string
	NodeLocation       string
	NodeVersion        string
}{
	Heartbeat:          "heartbeat",
	Mempool:            "mempool",
	MempoolBin:         "mempool_bin",
	NetworkSnapshot:    "network_snapshot",
	NetworkSnapshotBin: "network_snapshot_bin",
	Node:               "node",
	NodeLocation:       "node_location",
	NodeVersion:        "node_version",
}
