// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testNetworkSnapshotBins(t *testing.T) {
	t.Parallel()

	query := NetworkSnapshotBins()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testNetworkSnapshotBinsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNetworkSnapshotBinsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := NetworkSnapshotBins().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNetworkSnapshotBinsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NetworkSnapshotBinSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNetworkSnapshotBinsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := NetworkSnapshotBinExists(ctx, tx, o.Timestamp, o.Bin)
	if err != nil {
		t.Errorf("Unable to check if NetworkSnapshotBin exists: %s", err)
	}
	if !e {
		t.Errorf("Expected NetworkSnapshotBinExists to return true, but got false.")
	}
}

func testNetworkSnapshotBinsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	networkSnapshotBinFound, err := FindNetworkSnapshotBin(ctx, tx, o.Timestamp, o.Bin)
	if err != nil {
		t.Error(err)
	}

	if networkSnapshotBinFound == nil {
		t.Error("want a record, got nil")
	}
}

func testNetworkSnapshotBinsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = NetworkSnapshotBins().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testNetworkSnapshotBinsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := NetworkSnapshotBins().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testNetworkSnapshotBinsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	networkSnapshotBinOne := &NetworkSnapshotBin{}
	networkSnapshotBinTwo := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, networkSnapshotBinOne, networkSnapshotBinDBTypes, false, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}
	if err = randomize.Struct(seed, networkSnapshotBinTwo, networkSnapshotBinDBTypes, false, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = networkSnapshotBinOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = networkSnapshotBinTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NetworkSnapshotBins().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testNetworkSnapshotBinsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	networkSnapshotBinOne := &NetworkSnapshotBin{}
	networkSnapshotBinTwo := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, networkSnapshotBinOne, networkSnapshotBinDBTypes, false, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}
	if err = randomize.Struct(seed, networkSnapshotBinTwo, networkSnapshotBinDBTypes, false, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = networkSnapshotBinOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = networkSnapshotBinTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testNetworkSnapshotBinsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNetworkSnapshotBinsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(networkSnapshotBinColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNetworkSnapshotBinsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNetworkSnapshotBinsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NetworkSnapshotBinSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNetworkSnapshotBinsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NetworkSnapshotBins().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	networkSnapshotBinDBTypes = map[string]string{`Timestamp`: `bigint`, `Height`: `bigint`, `NodeCount`: `integer`, `ReachableNodes`: `integer`, `Bin`: `character varying`}
	_                         = bytes.MinRead
)

func testNetworkSnapshotBinsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(networkSnapshotBinPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(networkSnapshotBinAllColumns) == len(networkSnapshotBinPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testNetworkSnapshotBinsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(networkSnapshotBinAllColumns) == len(networkSnapshotBinPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NetworkSnapshotBin{}
	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, networkSnapshotBinDBTypes, true, networkSnapshotBinPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(networkSnapshotBinAllColumns, networkSnapshotBinPrimaryKeyColumns) {
		fields = networkSnapshotBinAllColumns
	} else {
		fields = strmangle.SetComplement(
			networkSnapshotBinAllColumns,
			networkSnapshotBinPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := NetworkSnapshotBinSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testNetworkSnapshotBinsUpsert(t *testing.T) {
	t.Parallel()

	if len(networkSnapshotBinAllColumns) == len(networkSnapshotBinPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := NetworkSnapshotBin{}
	if err = randomize.Struct(seed, &o, networkSnapshotBinDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NetworkSnapshotBin: %s", err)
	}

	count, err := NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, networkSnapshotBinDBTypes, false, networkSnapshotBinPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NetworkSnapshotBin struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NetworkSnapshotBin: %s", err)
	}

	count, err = NetworkSnapshotBins().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
