// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testNodeVersions(t *testing.T) {
	t.Parallel()

	query := NodeVersions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testNodeVersionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNodeVersionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := NodeVersions().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNodeVersionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NodeVersionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNodeVersionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := NodeVersionExists(ctx, tx, o.Timestamp, o.Bin, o.UserAgent)
	if err != nil {
		t.Errorf("Unable to check if NodeVersion exists: %s", err)
	}
	if !e {
		t.Errorf("Expected NodeVersionExists to return true, but got false.")
	}
}

func testNodeVersionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	nodeVersionFound, err := FindNodeVersion(ctx, tx, o.Timestamp, o.Bin, o.UserAgent)
	if err != nil {
		t.Error(err)
	}

	if nodeVersionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testNodeVersionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = NodeVersions().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testNodeVersionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := NodeVersions().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testNodeVersionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	nodeVersionOne := &NodeVersion{}
	nodeVersionTwo := &NodeVersion{}
	if err = randomize.Struct(seed, nodeVersionOne, nodeVersionDBTypes, false, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}
	if err = randomize.Struct(seed, nodeVersionTwo, nodeVersionDBTypes, false, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = nodeVersionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = nodeVersionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NodeVersions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testNodeVersionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	nodeVersionOne := &NodeVersion{}
	nodeVersionTwo := &NodeVersion{}
	if err = randomize.Struct(seed, nodeVersionOne, nodeVersionDBTypes, false, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}
	if err = randomize.Struct(seed, nodeVersionTwo, nodeVersionDBTypes, false, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = nodeVersionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = nodeVersionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testNodeVersionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNodeVersionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(nodeVersionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNodeVersionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNodeVersionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NodeVersionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNodeVersionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NodeVersions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	nodeVersionDBTypes = map[string]string{`Timestamp`: `bigint`, `Height`: `bigint`, `NodeCount`: `integer`, `UserAgent`: `character varying`, `Bin`: `character varying`}
	_                  = bytes.MinRead
)

func testNodeVersionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(nodeVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(nodeVersionAllColumns) == len(nodeVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testNodeVersionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(nodeVersionAllColumns) == len(nodeVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NodeVersion{}
	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, nodeVersionDBTypes, true, nodeVersionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(nodeVersionAllColumns, nodeVersionPrimaryKeyColumns) {
		fields = nodeVersionAllColumns
	} else {
		fields = strmangle.SetComplement(
			nodeVersionAllColumns,
			nodeVersionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := NodeVersionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testNodeVersionsUpsert(t *testing.T) {
	t.Parallel()

	if len(nodeVersionAllColumns) == len(nodeVersionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := NodeVersion{}
	if err = randomize.Struct(seed, &o, nodeVersionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NodeVersion: %s", err)
	}

	count, err := NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, nodeVersionDBTypes, false, nodeVersionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NodeVersion struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NodeVersion: %s", err)
	}

	count, err = NodeVersions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
