// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testReddits(t *testing.T) {
	t.Parallel()

	query := Reddits()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRedditsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRedditsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Reddits().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRedditsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RedditSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRedditsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RedditExists(ctx, tx, o.Date)
	if err != nil {
		t.Errorf("Unable to check if Reddit exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RedditExists to return true, but got false.")
	}
}

func testRedditsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	redditFound, err := FindReddit(ctx, tx, o.Date)
	if err != nil {
		t.Error(err)
	}

	if redditFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRedditsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Reddits().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRedditsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Reddits().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRedditsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	redditOne := &Reddit{}
	redditTwo := &Reddit{}
	if err = randomize.Struct(seed, redditOne, redditDBTypes, false, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}
	if err = randomize.Struct(seed, redditTwo, redditDBTypes, false, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = redditOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = redditTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Reddits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRedditsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	redditOne := &Reddit{}
	redditTwo := &Reddit{}
	if err = randomize.Struct(seed, redditOne, redditDBTypes, false, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}
	if err = randomize.Struct(seed, redditTwo, redditDBTypes, false, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = redditOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = redditTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testRedditsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRedditsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(redditColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRedditsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRedditsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RedditSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRedditsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Reddits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	redditDBTypes = map[string]string{`Date`: `timestamp without time zone`, `Subreddit`: `character varying`, `Subscribers`: `integer`, `ActiveAccounts`: `integer`}
	_             = bytes.MinRead
)

func testRedditsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(redditPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(redditAllColumns) == len(redditPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, redditDBTypes, true, redditPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRedditsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(redditAllColumns) == len(redditPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Reddit{}
	if err = randomize.Struct(seed, o, redditDBTypes, true, redditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, redditDBTypes, true, redditPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(redditAllColumns, redditPrimaryKeyColumns) {
		fields = redditAllColumns
	} else {
		fields = strmangle.SetComplement(
			redditAllColumns,
			redditPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RedditSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRedditsUpsert(t *testing.T) {
	t.Parallel()

	if len(redditAllColumns) == len(redditPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Reddit{}
	if err = randomize.Struct(seed, &o, redditDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Reddit: %s", err)
	}

	count, err := Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, redditDBTypes, false, redditPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Reddit struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Reddit: %s", err)
	}

	count, err = Reddits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
