// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testYoutubes(t *testing.T) {
	t.Parallel()

	query := Youtubes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testYoutubesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testYoutubesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Youtubes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testYoutubesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := YoutubeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testYoutubesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := YoutubeExists(ctx, tx, o.Date)
	if err != nil {
		t.Errorf("Unable to check if Youtube exists: %s", err)
	}
	if !e {
		t.Errorf("Expected YoutubeExists to return true, but got false.")
	}
}

func testYoutubesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	youtubeFound, err := FindYoutube(ctx, tx, o.Date)
	if err != nil {
		t.Error(err)
	}

	if youtubeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testYoutubesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Youtubes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testYoutubesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Youtubes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testYoutubesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	youtubeOne := &Youtube{}
	youtubeTwo := &Youtube{}
	if err = randomize.Struct(seed, youtubeOne, youtubeDBTypes, false, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}
	if err = randomize.Struct(seed, youtubeTwo, youtubeDBTypes, false, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = youtubeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = youtubeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Youtubes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testYoutubesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	youtubeOne := &Youtube{}
	youtubeTwo := &Youtube{}
	if err = randomize.Struct(seed, youtubeOne, youtubeDBTypes, false, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}
	if err = randomize.Struct(seed, youtubeTwo, youtubeDBTypes, false, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = youtubeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = youtubeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testYoutubesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testYoutubesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(youtubeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testYoutubesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testYoutubesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := YoutubeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testYoutubesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Youtubes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	youtubeDBTypes = map[string]string{`Date`: `timestamp without time zone`, `Subscribers`: `integer`, `ViewCount`: `integer`, `Channel`: `character varying`}
	_              = bytes.MinRead
)

func testYoutubesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(youtubePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(youtubeAllColumns) == len(youtubePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testYoutubesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(youtubeAllColumns) == len(youtubePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Youtube{}
	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, youtubeDBTypes, true, youtubePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(youtubeAllColumns, youtubePrimaryKeyColumns) {
		fields = youtubeAllColumns
	} else {
		fields = strmangle.SetComplement(
			youtubeAllColumns,
			youtubePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := YoutubeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testYoutubesUpsert(t *testing.T) {
	t.Parallel()

	if len(youtubeAllColumns) == len(youtubePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Youtube{}
	if err = randomize.Struct(seed, &o, youtubeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Youtube: %s", err)
	}

	count, err := Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, youtubeDBTypes, false, youtubePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Youtube struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Youtube: %s", err)
	}

	count, err = Youtubes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
