// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Block                    string
	BlockBin                 string
	Propagation              string
	Vote                     string
	VoteReceiveTimeDeviation string
}{
	Block:                    "block",
	BlockBin:                 "block_bin",
	Propagation:              "propagation",
	Vote:                     "vote",
	VoteReceiveTimeDeviation: "vote_receive_time_deviation",
}
