// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Blocks", testBlocksUpsert)

	t.Run("BlockBins", testBlockBinsUpsert)

	t.Run("Propagations", testPropagationsUpsert)

	t.Run("Votes", testVotesUpsert)

	t.Run("VoteReceiveTimeDeviations", testVoteReceiveTimeDeviationsUpsert)
}
